---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  MYPY_FORCE_COLOR: 1
  PY_COLORS: 1
  TOX_TESTENV_PASSENV: >-
    FORCE_COLOR
    MYPY_FORCE_COLOR
    NO_COLOR
    PY_COLORS
    PYTEST_THEME
    PYTEST_THEME_MODE
  TOX_PARALLEL_NO_SPINNER: 1

jobs:
  lint:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.12' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
      - name: Run ruff --verbose src
        run: ruff --verbose src
      - name: Run mypy --verbose src
        run: mypy --verbose src
      - name: Run black --verbose src
        run: black --verbose src

  test:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.python == '3.12' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[tests]
      - name: Run tests
        run: bcamp-dl --version

  check:
    if: always()
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
