---
name: Build

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  MYPY_FORCE_COLOR: 1
  PY_COLORS: 1
  TOX_TESTENV_PASSENV: >-
    FORCE_COLOR
    MYPY_FORCE_COLOR
    NO_COLOR
    PY_COLORS
    PYTEST_THEME
    PYTEST_THEME_MODE
  TOX_PARALLEL_NO_SPINNER: 1

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs:
      - test
    runs-on: ubuntu-latest
    environment: build
    permissions:
      id-token: write
    steps:
      - if: github.event.ref_type == 'tag'
        uses: actions/checkout@v3
      - if: github.event.ref_type != 'tag'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[build]
      - name: Build
        run: |
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          repository-url: https://test.pypi.org/legacy/
