---
name: Temp

on:
  push:

permissions:
  contents: read

jobs:
  temp:
    name: Temp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[build]

      - name: Build
        run: python -m build

      - name: Get Version
        id: version
        shell: bash
        run: |
          export VERSION=$(python -c "import sys;sys.path.append('src/bcamp_dl');from _version import version;print(version)")
          [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]] || exit 1
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION"
